---
title: "PubPol 475/750<br> Protest, Social Movements, Art, and Policy Change  <br><br><br>"
title-block-banner: "#001B35" # banner.png
title-block-banner-color: body-bg
format:
# pdf: default
 html:
   toc: true
   toc-location: left
   theme: michigan.scss
css: styles.css
execute:
  echo: false
  engine: knitr

---

Tuesday/Thursday 1:00–2:20 a.m., 1210 Weill Hall

Instructor: Devin Judge-Lord, <judgelor@umich.edu>, 715-204-4287

- Office hours: Tuesday, 2:30–3:30 p.m. and Thursdays, 3:30-4:30, 3215 Weill Hall

---

This class explores political science and sociology research on how protests and movements affect policy, focusing on 20th and 21st-century movements in the United States. It covers opportunity structure, movement organizations, issue framing, coalition building, and the relationship between movements and political parties.  It also explores the role of movement art in policy change through creating and curating movement art, culminating in an exhibition at the end of the semester.

This is a small upper-level reading-intensive seminar that requires coming to class prepared to discuss the reading. There are no quizzes, exams, or prescriptive rubrics. Assessment is based on your thoughtful engagement with the ideas in the reading and with my feedback on your writing and art and on the articulation of research-based theories of change underlying your exhibitions.

In 2026 and 2027, this class will be a collaboration with UMMA staff and their [American Ephemera](https://umma.umich.edu/blog/umma-and-the-labadie-collection-launch-ambitious-exhibition-series-on-american-protest-and-social-movements/) exhibit.
	


Links to course resources: 

- 🏛️ [Best practices for our classroom environment](best-practices)

- 🪶 [Assignment Guide](assignments)

- 📚 [Required books](#required-books)

-  📖  [Reading by week](#reading-by-week)

<!--
-  📓 [Glossary](glossary)
--> 

<!--
- [📅 Subscribe to the course calendar](https://calendar.google.com/calendar/u/0?cid=Y18wYTM2N2U5NDZkMzkyMTQxZjJhNDdmN2Y2MDhkNjBjN2E1N2I3ZTQ0ZTAzZjAyODk0NmM3YjU5ODBhOGY1MmE3QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20)

--> 
 
<!--
- [📅 Sign up for discussion opening, closing remarks, and paper meetings](https://calendar.app.google/WFMD6o2nrVtBGbgS9)
--> 

---

Syllabus updated: [`r Sys.Date() |> format("%B %d %Y")`](https://github.com/judgelord/PP495/commits/main/docs/syllabus.html). The current version is [here](syllabus.html).

<!--
This course advanced my understanding of the subject matter. Q1631*
My interest in the subject has increased because of this course. Q1632
I knew what was expected of me in this course. Q1633
I had a strong desire to take this course. Q4
As compared with other courses of equal credit, the workload for this course was (Much Lighter, Lighter, Typical, Heavier, Much Heavier). Q891
The instructor seemed well-prepared for class meetings. Q230
The instructor explained the material clearly. Q199
The instructor treated students with respect. Q217
--> 

	

# 🗺️  Objectives





This class covers research on the policy effects of various movements such as the marriage equality movement, the living wage movement, the Tea Party movement, <!--the American Indian Movement,--> the civil rights movement, the anti-communist movement, the environmental justice movement, the anti-war movement, the new right, and certain aspects of labor and suffrage/feminist/women's movements.


## ∴ Course Philosophy 

In designing this course, I proceed from several premises: 

1. It is worth knowing the **history** of our current policy debates and the **ideas and values** that the rhetoric of these policy debates evokes.

1. It is more interesting to explore **deeply rooted ideas** and see them in rhetoric than to stay at the level of rhetoric. This class is about politics and policy and only secondarily about rhetoric and communications. I don't want us to limit our thinking to what plays well in current mass media or elite discourse. I want you to develop a position on how you think politics should be reshaped. Then, let that inform your analysis of the rhetoric.

1. Individual action is good but insufficient; **collective action (and thus politics) is required**. This class is in the public policy school, and I am a political scientist. We are here to learn about the many ways social movements impact (or fail to impact) policy, not argue about whether policy and politics, in general, are useful for solving problems. 


# 🏛️ Learning Environment

Learning from each other is only possible if we show the respect due to our fellow citizens of this class.

To realize this goal, I expect us to respect our colleagues and cultivate inclusive discussions. This means that we must be careful not to mislead, degrade, interrupt someone who does not speak as much, or enforce hierarchies based on race, religion, ethnicity, nationality, gender expression, sexual orientation, or ability.

<!--[Best Practices for Navigating the Classroom Environment - 
Fall 2022](https://docs.google.com/document/d/1uSAbeIoEHqZwBzBlbDsz_jl5J_mapwoRxyOK1OGhBdM)--> 

## 📜 Ford School and University of Michigan Policies

**Ford School Inclusivity Statement:**
Members of the Ford School community represent a rich variety of backgrounds and perspectives. We are committed to providing an atmosphere for learning that respects diversity. While working together to build this community, we ask all members to: 

- share their unique experiences, values, and beliefs
- be open to the views of others
- honor the uniqueness of their colleagues
- appreciate the opportunity that we have to learn from each other in this community
- value one another’s opinions and communicate in a respectful manner
- keep confidential discussions that the community has of a personal (or professional) nature
- use this opportunity together to discuss ways in which we can create an inclusive environment in Ford - classes and across the UM community


Being a constructive member of a diverse community is always a learning process. The University has many resources to help us in this endeavor, including a [glossary of terms]( 
https://www.dropbox.com/sh/7whjk69ckv3h39r/AAAsKb3tOl4OulF63-mJsHa1a/Glossary%20of%20Terms?dl=0&preview=Clearinghouse+-+Glossary.pdf&subfolder_nav_tracking=1).

**Ford School Public Health Protection Policy.**  In order to participate in any in-person aspects of this course---including meeting with other students to study or work on a team project---you must follow all the public health safety measures and policies put in place by the State of Michigan, Washtenaw County, the University of Michigan, and the Ford School. Up-to-date information on U-M policies can be found on the  [U-M Health Response website](https://campusblueprint.umich.edu/).  It is expected that you will protect and enhance the health of everyone in the Ford School community by staying home and following self-isolation guidelines if you are experiencing any symptoms of COVID-19. 

**Student Mental Health and Wellbeing.**  The University of Michigan is committed to advancing the mental health and wellbeing of its students.  We acknowledge that a variety of issues, both those relating to the pandemic and other issues such as strained relationships, increased anxiety, alcohol/drug problems, and depression, can directly impact students’ academic performance and overall wellbeing. If you or someone you know is feeling overwhelmed, depressed, and/or in need of support, services are available. 

You may access the Ford School’s embedded counselor, Paige Ziegler (pziegler@umich.edu), and/or counselors and urgent services at [Counseling and Psychological Services (CAPS)](https://caps.umich.edu/) and/or [University Health Service (UHS)](https://www.uhs.umich.edu/mentalhealthsvcs).  Students may also use the Crisis Text Line (text '4UMICH' to 741741) to be connected to a trained crisis volunteer.  You can find additional resources both on and off campus through the [University Health Service](https://uhs.umich.edu/stressresources) and through [CAPS](https://caps.umich.edu/article/um-mental-health-resources).

**Student/Faculty Interaction Best Practices.** We strive to ensure a safe learning environment free from gender-based and sexual harassment, sexual violence, retaliation, and a hostile environment based on discrimination and intimidation. We make the following commitments:  

- To conduct office hours with the door open unless the student requests a closed-door meeting;
- To document meeting times with students so that this record can be reviewed.
- To meet students individually only at university venues;
- To conduct off-campus meetings only at places where alcohol is not served;
- To communicate electronically with students only on university platforms and not on social media, text, or non-university apps.
- For more information on resources for reporting sexual misconduct, please see [the faculty senate best practices for faculty interactions](https://facultysenate.umich.edu/wp-content/uploads/2022/08/BEST-PRACTICES-FOR-FACULTY-_-STUDENT-INTERACTIONS.pdf) and [U-M's page on Sexual and Gender-Based Misconduct](https://sexualmisconduct.umich.edu/).


**Accommodations for Students with Disabilities:**  
Accommodations for Students with Disabilities: The University of Michigan recognizes disability as an integral part of diversity and is committed to creating an inclusive and equitable educational environment for students with disabilities. Students who are experiencing a disability-related barrier should visit the Services for Students with Disabilities website. They can be reached at 734-763-3000 or ssdoffice@umich.edu. For students who are connected with SSD, accommodation requests can be made in Accommodate. If you have any questions or concerns, please contact your SSD Coordinator or visit SSD’s Current Student webpage. SSD considers aspects of the course design, course learning objects, and the individual academic and course barriers experienced by the student. Further conversation with SSD, instructors, and the student may be warranted to ensure an accessible course experience.

::: {.callout-important}
**If you require accommodations from SSD, please start that process quickly because it takes time. **
:::

**Academic Integrity:**  The Ford School academic community, like all communities, functions best when its members treat one another with honesty, fairness, respect, and trust. We hold all members of our community to high standards of scholarship and integrity. To accomplish its mission of providing an optimal educational environment and developing leaders of society, the Ford School promotes the assumption of personal responsibility and integrity and prohibits all forms of academic dishonesty, plagiarism, and misconduct. Academic dishonesty may be understood as any action or attempted action that may result in creating an unfair academic advantage for oneself or an unfair academic advantage or disadvantage for any other member or members of the academic community. Plagiarism involves representing the words, ideas, or work of others as one’s own in writing or presentations, and failing to give full and proper credit to the original source. Conduct, without regard to motive, that violates academic integrity and ethical standards will result in serious consequences and disciplinary action. The Ford School's policy of academic integrity can be found in the [MPP](https://www.dropbox.com/s/wuq2jfmbpflm4f2/FINAL%202023%20Masters%20Handbook.pdf?dl=0),  [BA](https://www.dropbox.com/s/zhllbd4vpfr439r/FINAL%202023%20BA%20Handbook.pdf?dl=0), and [Ph.D. Program](https://www.dropbox.com/s/06x1tzt1e32pjjw/FINAL%202023%20PHD%20Handbook.pdf?dl=0) handbooks. Additional information regarding academic dishonesty, plagiarism, and misconduct and their consequences is available at [U-M's academic-policies page]( http://www.rackham.umich.edu/current-students/policies/academic-policies/section11#112).



**Use of Technology:**  Students should follow instructions from their instructor as to acceptable use of technology in the classroom, including laptops, in each course. All course materials (including slides, assignments, handouts, pre-recorded lectures, or recordings of class) are to be considered confidential material and are not to be shared in full or in part with anyone outside of the course participants. Likewise, your own personal recording (audio or video) of your classes or office hour sessions is allowed only with the express written permission of your instructor.  If you wish to post course materials or photographs/videos of classmates or your instructor to third-party sites (e.g., social media), you must first obtain informed consent. Without explicit permission from the instructor and, in some cases, your classmates, the public distribution or posting of any photos, audio/video recordings, or pre-recordings from class, discussion section, or office hours, even if you have permission to record, is not allowed and could be considered academic misconduct.

Please review additional information and policies regarding [academic expectations and resources](https://intranet.fordschool.umich.edu/academic-expectations) at the Ford School of Public Policy.

See the end of the syllabus for information about our commitment to best practices of instructor/student interactions. 


## 📵 Technology in Class

No screens in class (except as an accommodation via the UM Services for Students with Disabilities office). Research shows that they inhibit learning^[
https://www.sciencedirect.com/science/article/pii/S1747938X18300101?via%3Dihub,
https://ila.onlinelibrary.wiley.com/doi/10.1002/rrq.527
https://osf.io/preprints/socarxiv/6z5pa_v1] and distract your colleagues. Out of respect to the instructor and your fellow students, put your phone away for the duration of class. 

You will not receive participation points for classes where you are on a screen during class time without permission. 

## 🛠️ Tools That Generate Text

You learn by doing work, and I assess your learning by the work you do. You may use tools to help craft your writing, but you must learn the crafts of constructive critique and persuasive writing to succeed in class. To add value to any employer or cause, you must craft arguments and recommendations that are significantly better than they would get by asking a [SALAMI](https://blog.quintarelli.it/2019/11/lets-forget-the-term-ai-lets-call-them-systematic-approaches-to-learning-algorithms-and-machine-inferences-salami/). I expect the same. 

Text extruded by large language models (LLMs) is, by construction, derivative of patterns of words already linked together on the internet. In some sense, everything we do is derivative of our experiences, but the generative process is very different for thinking subjects (you) than for a pre-trained language model. Language models are [excellent at helping us conform to grammar conventions^[I recommend <https://app.grammarly.com/>] but incapable of producing original critiques. If they produce something that sounds insightful, it is only because we are able to assign meaning to the strings of words they extrude. (It also probably sounds right because it resembles things already written by a human on the internet.) Language models have no sense of meaning and cannot judge the consistency, coherence, or logic of an argument.  I expect the work you produce to be yours and for you to stand by it as an intellectual project. No LLM can help you justify your thought process and reasoning. LLMs have no thought process and [do not reason](https://www.anildash.com//2023/06/08/ai-is-unreasonable/).
Language is always in flux, but I see "reasoning" and "intelligence" are misnomers when applied to LLMs. 

Beyond grammar conventions, I am not yet sure if LLMs are a helpful tool for the craft of persuasive writing or for learning this craft. I worry that they may constrain creativity by focusing our attention on problems and solutions that already exist and have already been frequently linked in the source material on which the LLMs are trained. Additionally, in many fields, including political science, rich white men are disproportionately the authors of the source texts. Uncritically using LLMs trained on biased source material risks reproducing those biases.

I basically agree with your colleague, [Siena Beres](https://www.michigandaily.com/statement/ai-ate-my-homework-my-experience-with-the-universitys-ai-toolkit/), that the university pushing you all to use chatbots is very likely not all it is hyped up to be. Some shortcuts are helpful. Some cause you to miss out on the important parts of the journey.

Good policy and political strategy rest on good evidence. LLMs can fabricate evidence. Even when the sources are real, unless it is an exact quote, LLMs cannot guarantee a reasonable link between a claim and a source (LLMs don't reason), only a statistically probable word order. Extruded text is often sensible, but there is no guarantee. Be careful. Work submitted with <mark>fake sources or made-up facts will get a 0</mark> for similar reasons that other forms of academic dishonesty make work worse than worthless. <!--The key recommendation of experts studying how students can effectively use LLMs is to craft a solid bibliography first and constrain generative tools to those sources. You will still have to do significant work to make sure that sources are used and cited appropriately, but this is much easier than finding real evidence to replace fake evidence and *then* making sure it is used and cited correctly.-->  
Thus, <mark>**references must be hyperlinked**</mark> whenever possible; I will check to make sure sources of evidence are used appropriately. 

If you use people or tools other than your brain and spelling/grammar checkers to string words together, you should be prepared to comment on what you used them for, what they got right, and what they got wrong. 

I reserve the right to discuss your papers in length with you if I have concerns that technological crutches are hindering your learning.

## 🛠️ Tools That Generate Images

I am more optimistic about the value of image-generating tools for this task because they require more thought and instruction from you. Like LLMs, they are essentially a tool of [collage](https://en.wikipedia.org/wiki/Collage). 

You are totally welcome to use image-generating tools at any step of your creative process. 

However, as the artist, you are responsible for understanding your source material. Thus, you should be able to comment on where the imagery is derived from and what it evokes. A reverse-image search of discrete portions of generated images may help you better understand the source material for the collage that a computer generated for you. 

You will probably want to come up with any words you want to appear on your posters yourself (for reasons discussed above).


Please also be mindful of the environmental cost of computation. Many things we do affect other people and places. Using computers in data centers to generate images is likely one of the most impactful things you may do.


# 🪶 Assignments 

Credit hours will be earned by attending two classes of $1.3\bar{3}$ hours each, reading and preparing written work outside of class for 6 to 9 hours per week, and a series of incremental assignments building to an exhibition of original art and accompanying theories of change. 

A key part of the process will be critiquing the work of others. Detailed instructions for each assignment are available in the [assignment guide](assignments). 


Most weeks, the assignments are incremental steps to your project. 

> <mark>**All assignments are to be submitted on Canvas.** </mark>



## Due Dates 

> <mark>**Discussion question posts are due Mondays and Wednesdays at 7 p.m.** </mark>

> <mark>**All other assignments and critiques are due Thursdays at 7 p.m.** </mark>

::: {.callout-important}
There is an incremental assignment building to your final project due almost <mark>every Thursday</mark>. 
:::

<!--
::: {.callout-tip}
[Subscribe to the due dates calendar here](https://calendar.google.com/calendar/u/0?cid=Y18wYTM2N2U5NDZkMzkyMTQxZjJhNDdmN2Y2MDhkNjBjN2E1N2I3ZTQ0ZTAzZjAyODk0NmM3YjU5ODBhOGY1MmE3QGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20).
:::
--> 

Below is the schedule of due dates. 

### Introductions (1%)

- Week 1 (Monday): Introduce yourself to the class with a short (20-30 second) video---feel free to be creative (1%) 

### Find your voice - 27% of final grade

In the first third of the class, you develop six exhibition ideas and attempt to write a theory of change for each. 

- Week 1: A list of **6** policies you would like to see changed, **3** organizations working to create each policy change, and one example of [ephemera](https://en.wikipedia.org/wiki/Ephemera) from each organization. (1%)^[Most organizations have an email list---I suggest signing up, both for the assignments in this class and your future career.] 
- Week 2: **six** 200-word **theories of change** (see [assignment guide](assignments)) for each of **six** of the ephemera from week one, **one** for each policy (in-class peer workshop) (1%) 
- Week 3: **Six** original sketches, **one** for each policy + a 200-word theory of change for each + annotated bibliography in footnotes (1%) 
- Week 4:  Peer critiques (2%)
  - UMMA visit
- Week 5: **Five** revised sketches, **one** for each 5 policies + a 200-word theory of change for each + annotated bibliography in footnotes (20%) 
- Week 6:
  - Meet with me about your ideas
  <!---[Sign up here](https://calendar.app.google/sF3Px1X8mNcNjFtQ8) --> 
  (part of the previous assignment grade)
  - Reflection post  (1%)
  
  <!--Reflection on either your experience with climate activism or feelings about climate change.-->
- At some point during the first half of the semester, present one of your ideas to the class (2-3 minutes each). Two students will pitch their ideas each week. This will give you practice testing out your argument and presentation skills (1%)

### Craft your message - 27% of final grade

In the middle third of the semester, you will narrow your focus to three ideas and then two ideas, and write the first half of each through multiple rounds of revision. 

- Week 7:  **Six** revised sketches, **two** for each of **three** policies + a 400-word theory of change for each + annotated bibliography in footnotes (1%)
- Week 8: Peer critiques (2%)
- Week 9: **Six** revised sketches, **three** for each of **two** + revised 400-word theory of change + annotated bibliographies in footnotes (1%)
  - Workshop at UMMA
- Week 10: Peer critiques (2%)
- Week 11:  **Six** revised sketches, **three** for each of **two** + revised 400-word theory of change + annotated bibliographies in footnotes  + updated revision spreadsheets (20%)
- Week 12: 
  - My feedback on your work
  - Reflection post (1%)

### Hone your critique - 23% of final grade

Through further rounds of revision, you will hone your critique, improving your logic and writing (writing can always be improved).


- Week 13:  **Six** revised sketches for **one** policy + **1-page** exhibition-formatted theory of change for each + annotated bibliographies in **ENDNOTES**  + updated revision spreadsheets (1%)
- Week 14: Peer critiques (2%)
   - Present at UMMA
- Week 15: Final exhibit + updated revision spreadsheet (20%)

::: {.callout-note}
I am mostly grading on 

1. How you engage with theories of policy change in the readings (and other academic readings you may do)
2. How you responded to feedback
:::


## Late Submissions

Because nearly all assignments are either revised versions of previous submissions that someone else must review on a tight timeline or peer reviews that your peers depend on in order to make revisions on a tight timeline, late work is not an option. 

- If you do not submit a revised version of your op-ed(s) on time, I will resubmit your previous version for review on your behalf. This will make sure you still get feedback on your work. If you submit by the end of the week, I will award partial points, but your reviewer is not expected to wait for the revised version to submit their review. 
- Late reviews are unfair to your classmates. If you do not submit a peer review on time, I will submit a review on your behalf, and you will not receive points for that review. 

Under extenuating circumstances, I will attempt to work out an alternative review cycle. This is much easier if I am the one reviewing a draft than if it is a draft submitted for peer review.


## Participation - 22% (24 classes X 1% per class - 2 pass days) 

- Discussion posts about at least one of the readings are due by <mark> 7 p.m. on Canvas Mondays and Wednesdays</mark> weeks 2-14. Late posts are not counted. Posts should be no more than 150 words and include (1)  a **one-sentence** summary of <mark> Your understanding of the argument(s) relevant to your question(s), (2) What you think about the argument(s), AND (3) Question(s) *about the reading(s)* that merit further discussion.</mark>  <!--TODO See my [guide for crafting a good discussion question]().--> 
When there are multiple readings, you need not ask a question about every reading, but do focus on the more substantive readings. Quotes and citations don't count toward the word limit.
- Participate in class discussion. Attendance is required. You must let me know *ahead of time* if you must miss class. 
- Summarize the discussion questions posed on Canvas for one class (2-3 minutes OR summarize what we have learned and how we have refined the points of debate at the end of one class (2-3 minutes)

[Sign up to summarize questions or what we learned here.](https://calendar.app.google/sF3Px1X8mNcNjFtQ8)


::: {.callout-note}
<mark>Discussion questions are graded</mark> on a 0-3 scale. 

Advice on writing good questions from Professor Rohde: 

Questions should model good intellectual practice; that is, not just a one-sentence question, but a few sentences providing some important framing or context. This could include, for example, an explanation of why the question is important (the stakes), an elaboration on the nuances of the question, etc. Reference to specific language in the text(s) is encouraged, and quotes are welcome. For material on the syllabus, simply cite the author and page; for materials beyond the syllabus, please include a full reference. 

Types of questions: 

- Clarification/Comprehension (e.g., What does X mean? --- This should not be answered with a quick internet search --- an internet search yielding contradictory plausible answers is evidence that it is a good question)
- Analytical/Interpretive (e.g., How does X evidence relate to Y point?)
- Synthetic/Evaluative (e.g., Are you convinced by the author’s argument that X? ) If you choose this question, be sure to say why the argument is provocative or has important implications. If you think a statement is obviously correct or trivial, then it is not worth discussing whether we agree with it.
- Connective/Comparative (e.g., How does X’s argument compare to Y’s we read last week?) If you choose this question, point us in the direction of some key similarities or differences. 
- Provocative/Argumentative (e.g., Doesn’t evidence X undermine author’s point Y?!)
- Applied/Extended (e.g., Does X point help explain current problem Y?) If you choose this question, be sure to indicate why or how the comparison is relevant. I.e., don’t use this as a mindless invitation to extend an analysis across policy problems.
:::

<!--
Here are some example discussion questions: 

> [Clarification] Battistoni and Mann argue that the Biden Administration's linking of concerns about climate and the rising power of China led to "the legitimation of a mode of state capitalism that would have been unthinkable in the inner circles of American policymaking a few years ago." I am a bit confused by the jargon here. My understanding is that this is what they mean by "Bidenomics," but they also talk about "Bidenomics" as "industrial policy" when talking about the IRA. Do "state capitalism" and "industrial policy" mean the same thing here? Or can you have one without the other? Finally, how does this relate to the concept of "political capitalism" discussed at the beginning of the article?

> [Analytical] Contrasting investments in green infrastructure with proposed policies targeting child care that were cut from the IRA, Battistoni and Mann ask, "Why did [green infrastructure investments] squeak through, while proposed investments in 'care infrastructure' and other social welfare programs were abandoned?" I am not sure which of the answers they offer is the better explanation. They seem to offer two answers: (1) that Biden was pursuing "a classic strategy of (re)industrialization" and (2) that Senator Manchin's "decisive role in the IRA's passage means that it relies almost entirely on incentives for investments in green tech." Which is more to blame? Biden's priorities or Manchin's? What evidence do we have either way?

> [Evaluative] Battistoni and Mann provocatively argue that "there is little to distinguish the IRA's 'carrots-only' strategy from Obama's notorious 'all of the above' energy policy." I think I see what they are saying, but I don't think it is accurate. I also think it contradicts their main argument about how we have entered a new era of climate politics. Are you persuaded that Obama and Biden's climate policy strategies are more similar than they are different? [For context, recall that the two most prominent features of Obama's climate policy were the Clean Power Plan regulations on power plants and the Waxman-Markey cap and trade bill.] In what sense is this statement persuasive? In what sense is it not? More generally, much has been made (including in this article) about the new era of industrial policy. In what sense is it new? In what sense is it more of the same?

> [Connective] In the Volts podcast about the Farm Bill, we learned that U.S. ag policy resembles the "industrial policy" that the other readings used to describe the energy policy of both the Biden and Trump administrations. This made me curious about the connections between these two kinds of policy. Are there insights from how ag policy has developed and how political coalitions have formed that suggest what we can expect to see in energy policy, where fuel sources are increasingly shaped by the state, similar to how our food sources have been for decades? Are there fundamental differences in ag and energy policy, politics, or industry that make them difficult to compare? Or is there a version of the Farm bill that could emerge for Energy? Can we imagine what a regular bipartisan 5-year Energy Bill would look like? What are the political coalitions for this?

> [Provocative] Several of this week's readings talked about the political theory of why various IRA policies should create durable political collections (e.g., Battistoni and Mann and the interview with Sonia Aggarwal). Yet, Harris did not campaign much on climate, Trump was elected on a platform that included repealing the IRA, and (despite most of the money going to their districts) nearly every Republican member of Congress voted to scrap most IRA provisions. Is the lesson that the political strategy of the IRA to build a durable coalition and "lock-in" policy is a failure? To what extent should we conclude that the underlying theory of what makes a policy durable is wrong? To take a step back, what exactly was the theory of why IRA provisions would not be repealed? Why did so many people think this? Does the evidence we have from the debates over its repeal undermine the theory?

--> 



### Make-up policy 

You get two days to take a pass on posting a discussion question and/or participating in class. Even if you are taking a pass on participation, I hope you will still come to class. If you are taking a pass and don't want me to call you into the conversation, just let me know ahead of time.

Pass days will initially appear as "0" on Canvas, but I will adjust participation points when I calculate your final scores in Canvas. 

Beyond your two pass days, I allow you to make up two additional days:

- If you know that you will miss class, write a `1-page reflection` on the readings and share it with the class **with your discussion post.**
- If you unexpectedly miss class, post a `1-page reflection on the readings **AND schedule a time to discuss the readings with me**` (ideally, during office hours)

Beyond four missed classes (two passes, two make-ups), I  only allow make-ups in very extenuating circumstances. Participation is a core part of this class, and the entire class is deprived of your perspective when you are not with us. 



#	 📚 Required Books

You must have a physical copy of several books to bring to class: 

> [*The Politics of Common Sense: How Social Movements Use Public Discourse to Change Politics and Win Acceptance* by Deva Woodly (2015, Oxford University Press)](https://global.oup.com/academic/product/the-politics-of-common-sense-9780190203986)

> *Policy Paradox:  The Art of Political Decision Making* by Deborah Stone
 
> Skocpol, T., & Williamson, V. (2011). The Tea Party and the Remaking of Republican Conservatism. Oxford University Press.

> Heaney, M. T., & Rojas, F. (2015). Party in the street: The antiwar movement and the Democratic Party after 9/11. Cambridge University Press.

<!--- McAdam, D. (1999). Political process and the development of Black insurgency, 1930-1970 (2nd ed.). University of Chicago Press. --> 

> Reckoning: Black Lives Matter and the Democratic Necessity of Social Movements by Deva R. Woodly



The other readings will be available for free online (you may need to go through the library website for journal articles) or on Canvas.



Other books you may find useful: 

- *Politics is for Power* by Eitan Hersh
- *Rules for Radicals* by Saul Alinsky
- [*Politics: The Central Texts* by Roberto Mangabeira Unger (1997, Verso Books)](https://www.versobooks.com/products/1570-politics)



# ℹ Resources 

## American Government Module

If you are looking for more foundation in how government works, the Ford School organized an Intro to American Government Module taught by Political Science Ph.D. candidate Ciera Hammond: 

- [Day 1](http://leccap.engin.umich.edu/leccap/player/r/jdCaYX)
- [Day 2](http://leccap.engin.umich.edu/leccap/player/r/r4jN5e)
- [Day 3](http://leccap.engin.umich.edu/leccap/player/r/bSYi7Y)
- [Day 4](http://leccap.engin.umich.edu/leccap/player/r/fANcTy)

## Social movement topics not covered by this class 

Sports

- ["Sports, Race, Social Movements, and Social Change" by Douglas Hartmann](https://www.annualreviews.org/content/journals/10.1146/annurev-soc-090324-025141)


Organizing 

-["Spadework: On political organizing" by Alyssa Battistoni ](https://www.nplusonemag.com/issue-34/politics/spadework/)


Present-day movements in the United States 

- [*The Resistance*, Edited by David S. Meyer and Sidney Tarrow](https://global.oup.com/academic/product/the-resistance-9780190886189?cc=gb&lang=en&)

Movements outside the United States 

- [Why Civil Resistance Works: The Strategic Logic of Nonviolent Conflict (New York, NY: Columbia University Press, August 2011).](https://www.ericachenoweth.com/research/wcrw)

---

# 📖 Reading by Week


> Each week's required readings are indented and marked with a grey sidebar. I also often note "resources" or "further readings" with bullets---these are not required readings.


🎧 Most weeks include audio content, either in addition to or as an alternative to required reading. Pay attention to the minutes assigned. Some podcasts keep going, and you don't need to keep listening.



I have intentionally put a wide range of perspectives on the syllabus, sometimes in conversation.

There are some questions we will ask of every reading: 

- What is the author's argument? 
- What do you think about it? 
- Does it apply elsewhere? 
- What does it imply for what we should do? 

Come to class ready to answer these questions. 

If you hit a paywall on a link from the syllabus:

1. Look to see if it says `(Canvas->Perusall)` next to it. These readings should be on Perusall <!-- in the "files/readings" folder on Canvas.--> If they are not, please let me know ASAP.  
2. Make sure that you are logged in to get library access to journals. You can also search for the journal on the library website.   
3. If 1 & 2 don't work, please let me know ASAP so that I can make sure you all have access. Sometimes, paywalls don't pop up for me because of some cached credentials, and I don't realize that the content is paywalled. You should not pay for any of the online content for this course. 
There are many "further" readings, and some required readings (especially the longer academic articles) say "skim." Here is advice on [how to read political science from Amelia Hoover Green](https://www.ameliahoovergreen.com/uploads/9/3/0/9/93091546/howtoread.pdf) and [how to skim from Jessica Calarco](https://www.jessicacalarco.com/tips-tricks/2018/9/2/beyond-the-abstract-reading-for-meaning-in-academia).




## Week 1: 

### Tuesday: Introductions and Syllabus Review 


> Please read <mark> the entire syllabus</mark> before class---this is your chance to ask questions about the assignments and readings.

> [The success of nonviolent civil resistance: Erica Chenoweth at TEDxBoulder](https://www.youtube.com/watch?v=YJSehRlU34w)


::: {.callout-note collapse="true" title="Further reading"}
- A longer interview on nonviolent civil resistance research with Chenoweth:  [How to Change the World, Hidden Brain](https://www.hiddenbrain.org/podcast/how-to-change-the-world/)
::: 


### Tuesday: in-class [best-practices exercise](best-practices.html)

- What are you hoping to get out of this semester?
- What aspects of the discussion environment will help achieve these goals? 
- What has been your personal experience with protest, social movement discourse, and policy? What motivates you to do something? What makes you not want to get involved? 


## Week 2:



::: {.callout-note collapse="true" title="Further reading"}
*Civil Resistance: What Everyone Needs to Know* by Erica Chenoweth
Chapter 1: What is Civil Resistance?
Chapter 2: How Civil Resistance Works
:::

- To what extent have climate movements been effective, and why?
- To what extent are the underlying features of U.S. climate politics outlined by McAdam in 2017 still true? 

### Tuesday: Opportunity Structure and Mobilizing Structures 

> To Discuss: Research: [McAdam, Doug. 2017. “Social Movement Theory and the Prospects for Climate Change Activism in the United States.” *Annual Review of Political Science* 20:189–2008](https://www.annualreviews.org/content/journals/10.1146/annurev-polisci-052615-025801)


::: {.callout-note collapse="true" title="Further reading"}
- [Generation Green New Deal: The Pelosi Sit-In (Political Climate 2020)](https://www.politicalclimatepodcast.com/episodes/episode/22947545/generation-green-new-deal-the-pelosi-sit-in)
:::


### Thursday: 


> Stone, Chapter 1

> To Discuss: Research: [Chapter 1. Deva Woodly. 2015. The Politics of Common Sense: How Social Movements Use Public Discourse to Change Politics and Win Acceptance, Oxford University Press.](https://global.oup.com/academic/product/the-politics-of-common-sense-9780190203986?cc=us&lang=en&)

## Week 3: Efficiency and Welfare

## Tuesday

> Stone, Chapter 3-4: Efficiency and Welfare

> Woodly: Chapter Two: A Tale of Two Movements - Living Wage

## Thursday 

> TBD 

## Week 4: Equity and Equality

> Stone, Chapter 2: Equity

> Woodly, Chapter Three: A Tale of Two Movements- Marriage Equality



## Thursday at UMMA 



## Week 5: Theories of Change


Woodly

Chapter Four: The Discursive Architecture of Resonance

Chapter Five: Political Acceptance and the Process of Political Change

Chapter Six: From Marginal to Mainstream


::: {.callout-note collapse="true" title="Further reading"}
Movement demands (Sanders 1999; Htun & Weldon 2012; Woodly 2015, 2022; Sinha 2016; Thurston 2018; Forrester 2022; Tarrow 2022) 
:::

## Week 6:  The Tea Party

### Tuesday

> Stone, Chapter 5-6: Liberty & Security

> Woodly, Conclusion: After Acceptance - the Tea Party, Occupy & Prospects for political transformation


### Thursday 


> Skocpol, T., & Williamson, V. (2011). The Tea Party and the remaking of Republican conservatism. Oxford University Press.  Introduction, Chapters 1 & 2

> SKIM [Do Political Protests Matter? Evidence from the Tea Party Movement](https://scholar.harvard.edu/files/shoag/files/dopoliticalprotestsmatterevidencef_preview.pdf) The *Quarterly Journal of Economics*, Volume 128, Issue 4, November 2013, Pages 1633–1685 <https://doi.org/10.1093/qje/qjt021>


## Week 7: Vehicles 

### Tuesday: Social movement organizations, grass roots, and grass tops

> Stone, Chapters 7 and 10

> Skocpol, T., & Williamson, V. (2011). The Tea Party and the remaking of Republican conservatism. Oxford University Press.  Chapter 3

<!--
> TBD on Unions?
--> 

### Thursday: Parties 


> Schlozman, D. J. (2015). When movements anchor parties: Electoral alignments in American history. Princeton University Press. (1-49)


::: {.callout-note collapse="true" title="Further reading"}
- Skocpol 2006
:::

## Week 8 Civil Rights

### Tuesday 

> Stone, Chapter 15: Rights 

> McAdam, D. (1999). Political process and the development of Black insurgency, 1930-1970 (2nd ed.). University of Chicago Press.
 (p. TBD)


### Thursday

> McAdam, D. (1999). Political process and the development of Black insurgency, 1930-1970 (2nd ed.). University of Chicago Press.
 (p. TBD)



## Week 9: Tactics 

### Tuesday: Protest

>  Gillion, D. Q. (2013). The political power of protest: Minority activism and shifts in public policy. Cambridge University Press. (p. 1-38)

> When Protest Makes Policy
How Social Movements Represent Disadvantaged Groups
By Laurel Weldon, Introduction and Chapter 1 <!---Chapter 2--> 

>  [Gause 2022, Chapter 1, The Promise of Protest](https://www.cambridge.org/core/services/aop-cambridge-core/content/view/F80BB473DA827BC0A449880ABC3C1DE5/9781316513576c1_1-18.pdf/the-promise-of-protest.pdf)

> SKIM Wasaw (2020) "Agenda Seeding: How 1960s Black Protests Moved Elites, Public Opinion and Voting" (https://www.cambridge.org/core/journals/american-political-science-review/article/agenda-seeding-how-1960s-black-protests-moved-elites-public-opinion-and-voting/136610C8C040C3D92F041BB2EFC3034C)



::: {.callout-note collapse="true" title="Further reading"}
- Wilentz 2003
- Sinha 2015
:::

### Thursday: Art 

> Meet at UMMA 


<!--- ### Week 10: Labor (IF I DELETE CLIMATE CHANGE AND PUSH EVERYTHING BACK)---> 


## Week 10: Anti-communism and the New Right 

### Tuesday 

> Stone, Chapter 16: Powers 

> Schlozman, D. J. (2015). When movements anchor parties: Electoral alignments in American history. Princeton University Press, Chapter 4 (77-107)

### Thursdy

> TBD

::: {.callout-note collapse="true" title="Further reading"}
- [Black Struggle, Red Scare: Segregation and Anti-Communism in the South, 1948--1968](https://www.google.com/books/edition/Black_Struggle_Red_Scare/gGpMrxnZZHEC?hl=en&gbpv=1&dq=anti+communism&pg=PP11&printsec=frontcover)
- [*Anti-communism and popular culture in mid-century America* by Cynthia Hendershot](https://www.google.com/books/edition/Anti_Communism_and_Popular_Culture_in_Mi/RSy1CgAAQBAJ?hl=en&gbpv=1&dq=anti+communism&pg=PP1&printsec=frontcover)
:::

## Week 11: Anti-war 

> Heaney, M. T., & Rojas, F. (2015). Party in the street: The antiwar movement and the Democratic Party after 9/11. Cambridge University Press.


## Week 12: Environmental Justice

> People of color [raised] social justice concerns such as self-determination, sovereignty, human rights, social inequality, loss of land base, limited access to natural resources, and disproportionate impacts of environmental hazards and linked them with traditional working-class environmental concerns such as worker rights and worker health and safety to develop an environmental justice agenda. (Taylor, p. 1)


>  To Discuss: ["Race, Class, Gender, and American Environmentalism. US Forest Service General Technical Report PNW-GTR-534" (2002) by Dorceta Taylor](https://doi.org/10.2737/PNW-GTR-534) <!--could also go under movements--> (1-41)

::: {.callout-note collapse="true" title="Further reading"}
- [Racism as a Motivator for Climate Justice, Mark A. Mitchell, *Daedalus* Fall 2020](https://www.amacad.org/publication/racism-motivator-climate-justice)
- [Bringing Environmental Justice into Government Rulemaking, with Ann Wolverton (Resources Radio, 2023)](https://www.resources.org/resources-radio/bringing-environmental-justice-into-government-rulemaking-with-ann-wolverton/) (32 min) 🎧
- Bullard, R. D. (2005). *The quest for environmental justice: Human rights and the politics of pollution*
- [Putting more climate philanthropy toward economic and racial justice: A conversation with Abdul Dosunmu about the Climate Funders Justice Pledge. (Volts, 2023)](https://www.volts.wtf/p/putting-more-climate-philanthropy) (48 min) 🎧 
- [*Roosevelt Project Gulf Coast case* (2022) by Jason Beckfield et al.  1-30](https://ceepr.mit.edu/wp-content/uploads/2022/12/2022-The-Roosevelt-Project-Gulf-Coast-Case-Study.pdf)
- [Less Talk, More Walk: Why Climate Change Demands Activism in the Academy](https://direct.mit.edu/daed/article/149/4/151/94866/Less-Talk-More-Walk-Why-Climate-Change-Demands)
- *Fighting in a World on Fire* by Malm
- *Climate Change as Class War* by Huber 
:::

## Week 13: Movements & Democracy 

Reckoning: Black Lives Matter and the Democratic Necessity of Social Movements by Deva R. Woodly

### Tuesday

Introduction + Chapters 1-3

### Thursday 

Chapters 4, 5, and Conclusion


## Week 14

### Tuesday 

> In Class Presentations

### Thursday at UMMA 


## Week 15

### Tuesday: Wrap up

---

<!--exclude: true-->

## More Information on Student Instructor Best Practices

We will conduct office hours with my door open unless you request otherwise.

Students who wish to have confidential conversations with me may schedule a private meeting via Zoom or may ask to have a closed-door meeting. But this closed-door meeting must be made on your request in writing, even on the spot. I will never suggest a closed-door meeting myself because of the power dynamic.

We will document all pre-scheduled meetings between the instructor and the student via Google Calendar (or other software) and/or university email.

Students who email to request an office hour appointment should expect to receive an email confirmation or a Google Calendar (or other software) invitation from me, or, upon my email confirmation and request, may send me a Google Calendar (or other software) invitation for this meeting. The purpose is to provide a permanent record of the meeting and to ensure that all class activities are documented and transparent. Students who choose to drop by for informal meetings are welcome to do so, but there will be no documentation provided. (See above for open-door policy.)

We will choose meeting locations and conduct meetings with student and instructor safety in mind.

We will ensure that all individual meetings between the instructor/student will take place at university venues.

We will ensure that all off-campus meetings, trips, or events engage with the course material.

Off-campus meetings will not involve alcohol or take place at locations that serve alcohol. If the class goes out for a meal, it will be at a cafe or restaurant that does not serve alcohol. The location/day/time of any off-campus meetings between the instructor and students will be documented in Google Calendar (or other software).

We, the instructors, will conduct all individual communications using the University platforms of email, Canvas, Slack, or Piazza, with the caveat that we may use non-university platforms set up by students (such as GroupMe) only if they include all students in the class.

There will be no instructor-student private communications on any non-University platforms, such as social media, GroupMe, WhatsApp, etc.

For more information on resources for reporting sexual misconduct, please see [the faculty senate best practices for faculty interactions](https://facultysenate.umich.edu/wp-content/uploads/2022/08/BEST-PRACTICES-FOR-FACULTY-_-STUDENT-INTERACTIONS.pdf) and [U-M's page on Sexual and Gender-Based Misconduct](https://sexualmisconduct.umich.edu/).
